gateways:
    local:
        connection:
            type: duckdb
            database: data/catalog/catalog.db

default_gateway: local

model_defaults:
    dialect: duckdb, normalization_strategy=case_sensitive
    